# Generated by Django 5.0.4 on 2024-05-06 16:18

import Admin.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salutation', models.CharField(max_length=6)),
                ('first_name', models.CharField(max_length=32)),
                ('middle_name', models.CharField(max_length=32)),
                ('last_name', models.CharField(max_length=32)),
                ('email', models.EmailField(max_length=64)),
                ('district', models.CharField(max_length=12)),
                ('subdiv', models.CharField(max_length=12)),
                ('block', models.CharField(max_length=12)),
                ('address', models.CharField(max_length=64)),
                ('dob', models.DateField(blank=True)),
                ('doc', models.FileField(upload_to=Admin.models.user_file_storage)),
            ],
        ),
        migrations.CreateModel(
            name='AdminUser',
            fields=[
                ('phno', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('admin_type', models.CharField(max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stauts', models.CharField(max_length=10)),
            ],
        ),
    ]
