# Generated by Django 5.0.4 on 2024-05-06 16:38

import divisions.helpers
import django.core.validators
import tempdb.helpers
import tempdb.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('phone_number', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('salutation', models.CharField(max_length=6)),
                ('first_name', models.CharField(max_length=32)),
                ('middle_name', models.CharField(blank=True, max_length=32)),
                ('last_name', models.CharField(blank=True, max_length=32)),
                ('email', models.EmailField(blank=True, max_length=64)),
                ('district', models.CharField(max_length=12, validators=[divisions.helpers.check_district])),
                ('subdiv', models.CharField(max_length=12, validators=[divisions.helpers.check_subdivision])),
                ('block', models.CharField(max_length=12, validators=[divisions.helpers.check_block])),
                ('address', models.CharField(max_length=64)),
                ('dob', models.DateField(blank=True)),
                ('dtype', models.CharField(max_length=3, validators=[tempdb.helpers.check_type])),
                ('doc', models.FileField(blank=True, null=True, upload_to=tempdb.models.cfile, validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png'])])),
                ('rejected', models.BooleanField(default=False)),
                ('processed', models.BooleanField(default=False)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
        ),
    ]
