# Generated by Django 5.0.4 on 2024-05-07 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tempdb', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='processed',
        ),
        migrations.RemoveField(
            model_name='user',
            name='rejected',
        ),
        migrations.AddField(
            model_name='user',
            name='remarks',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(default='processing', max_length=10),
        ),
    ]
